# Classification Exercises

### 1. In a jupyter notebook, classification_exercises.ipynb, use a python module (pydata or seaborn datasets) containing datasets as a source from the iris data. Create a pandas dataframe, df_iris, from this data.

- print the first 3 rows
- print the number of rows and columns (shape)
- print the column names
- print the data type of each column
- print the summary statistics for each of the numeric variables. 
    
   Would you recommend rescaling the data based on these statistics?

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_iris = sns.load_dataset('iris')

In [3]:
type(df_iris)

pandas.core.frame.DataFrame

In [4]:
#print the first 3 rows
df_iris.head(3) 

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [5]:
#print the number of rows and columns (shape)
df_iris.shape

(150, 5)

In [6]:
#print the column names
df_iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [7]:
#print the data type of each column
df_iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [8]:
#print the summary statistics for each of the numeric variables.
df_iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### Would you recommend rescaling the data based on these statistics?

### -Yes

### 2. Read the Table1_CustDetails table from the Excel_Exercises.xlsx file into a dataframe named df_excel.

- assign the first 100 rows to a new dataframe, df_excel_sample
- print the number of rows of your original dataframe
- print the first 5 column names
- print the column names that have a data type of object
- compute the range for each of the numeric variables.

In [9]:
 df_excel = pd.read_excel('Table1_CustDetails.xlsx', sheet_name='Table1_CustDetails')
    

In [10]:
 df_excel.head()

customer_id  gender  is_senior_citizen partner dependents  phone_service  \
0  0002-ORFBO  Female                  0     Yes        Yes              1   
1  0003-MKNFE    Male                  0      No         No              2   
2  0004-TLHLJ    Male                  0      No         No              1   
3  0011-IGKFF    Male                  1     Yes         No              1   
4  0013-EXCHZ  Female                  1     Yes         No              1   

   internet_service  contract_type      payment_type  monthly_charges  ...  \
0                 1              1      Mailed check             65.6  ...   
1                 1              0      Mailed check             59.9  ...   
2                 2              0  Electronic check             73.9  ...   
3                 2              0  Electronic check             98.0  ...   
4                 2              0      Mailed check             83.9  ...   

   has_phone has_internet  has_phone_and_internet  partner_dependents  \
0       True         True                    True                   3   
1       True         True                    True                   0   
2       True         True                    True                   0   
3       True         True                    True                   1   
4       True         True                    True                   1   

               start_date  avg_monthly_charge  contract_type.1  \
0 2020-11-09 21:43:43.104                65.6           1 Year   
1 2020-11-09 13:46:58.656                59.9   Month-to-Month   
2 2021-04-18 09:42:13.248                73.9   Month-to-Month   
3 2020-07-23 19:16:50.304                98.0   Month-to-Month   
4 2021-05-07 01:23:48.480                83.9   Month-to-Month   

          phone_type  internet_type Unnamed: 24  
0           One Line            DSL         NaN  
1  Two or More Lines            DSL         NaN  
2           One Line    Fiber Optic         NaN  
3           One Line    Fiber Optic         NaN  
4           One Line    Fiber Optic         NaN  

[5 rows x 25 columns]

In [11]:
df_excel.shape

(7049, 25)

In [12]:
df_excel_sample = df_excel.head(100)

In [14]:
df_excel_sample.shape

(100, 25)

In [27]:
df_excel_sample.columns[5]

'phone_service'

In [36]:
df_excel_sample.dtypes

customer_id                       object
gender                            object
is_senior_citizen                  int64
partner                           object
dependents                        object
phone_service                      int64
internet_service                   int64
contract_type                      int64
payment_type                      object
monthly_charges                  float64
total_charges                    float64
churn                             object
tenure                           float64
is_female                           bool
has_churned\n                       bool
has_phone                           bool
has_internet                        bool
has_phone_and_internet              bool
partner_dependents                 int64
start_date                datetime64[ns]
avg_monthly_charge               float64
contract_type.1                   object
phone_type                        object
internet_type                     object
Unnamed: 24     

In [37]:
df_cols_object_type_bool = df_excel_sample.dtypes == 'object'
df_cols_object_type_bool

customer_id                True
gender                     True
is_senior_citizen         False
partner                    True
dependents                 True
phone_service             False
internet_service          False
contract_type             False
payment_type               True
monthly_charges           False
total_charges             False
churn                      True
tenure                    False
is_female                 False
has_churned\n             False
has_phone                 False
has_internet              False
has_phone_and_internet    False
partner_dependents        False
start_date                False
avg_monthly_charge        False
contract_type.1            True
phone_type                 True
internet_type              True
Unnamed: 24               False
dtype: bool

In [38]:
object_type_cols = df_excel_sample.dtypes[df_cols_object_type_bool]
object_type_cols

customer_id        object
gender             object
partner            object
dependents         object
payment_type       object
churn              object
contract_type.1    object
phone_type         object
internet_type      object
dtype: object

In [39]:
range_monthly_charges = df_excel.monthly_charges.max() - df_excel.monthly_charges.min()
range_monthly_charges

100.5

In [40]:
range_total_charges = df_excel.total_charges.max() - df_excel.total_charges.min()
range_total_charges

8666.0

In [41]:
range_avg_monthly_charges = df_excel.avg_monthly_charge.max() - df_excel.avg_monthly_charge.min()
range_avg_monthly_charges

118.75

In [42]:
range_tenure = df_excel.tenure.max() - df_excel.tenure.min()
range_tenure

79.34177215

In [43]:
url = "https://gist.githubusercontent.com/ryanorsinger/3fce5a65b5fb8ab728af5192c7de857e/raw/a0422b7b73749842611742a1064e99088a47917d/clean_telco.csv"
df_excel = pd.read_csv(url, index_col="id")

# 3. Read the data from this google sheet into a dataframe, df_google

- print the first 3 rows
- print the number of rows and columns
- print the column names
- print the data type of each column
- print the summary statistics for each of the numeric variables
- print the unique values for each of your categorical variables

In [48]:
sheet_url = "https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit?usp=sharing"

csv_export_url = sheet_url.replace('/edit?usp=sharing', '/export?format=csv')

df_google = pd.read_csv(csv_export_url)
df_google.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [49]:
df_google.shape

(891, 12)

In [52]:
df_google.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [53]:
df_google.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [54]:
df_google.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [55]:
df_google.Survived.unique()

array([0, 1])

In [56]:
df_google.Pclass.unique()

array([3, 1, 2])

In [57]:
df_google.Sex.unique()

array(['male', 'female'], dtype=object)

In [58]:
df_google.SibSp.unique()

array([1, 0, 3, 4, 2, 5, 8])

In [59]:
df_google.Parch.unique()

array([0, 1, 2, 5, 3, 4, 6])

In [60]:
df_google.Cabin.unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [61]:
df_google.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)